const MOVE_URL = "https://raw.githubusercontent.com/Purukitto/pokemon-data.json/master/moves.json";
const STORAGE_KEY = "boss-creator-v1";
const games = [["Gen 1","Pokémon Red"],["Gen 1","Pokémon Blue"],["Gen 1","Pokémon Yellow"],["Gen 2","Pokémon Gold"],["Gen 2","Pokémon Silver"],["Gen 2","Pokémon Crystal"],["Gen 3","Pokémon Ruby"],["Gen 3","Pokémon Sapphire"],["Gen 3","Pokémon Emerald"],["Gen 3","Pokémon FireRed"],["Gen 3","Pokémon LeafGreen"],["Gen 4","Pokémon Diamond"],["Gen 4","Pokémon Pearl"],["Gen 4","Pokémon Platinum"],["Gen 4","Pokémon HeartGold"],["Gen 4","Pokémon SoulSilver"],["Gen 5","Pokémon Black"],["Gen 5","Pokémon White"],["Gen 5","Pokémon Black 2"],["Gen 5","Pokémon White 2"],["Gen 6","Pokémon X"],["Gen 6","Pokémon Y"],["Gen 6","Pokémon Omega Ruby"],["Gen 6","Pokémon Alpha Sapphire"],["Gen 7","Pokémon Sun"],["Gen 7","Pokémon Moon"],["Gen 7","Pokémon Ultra Sun"],["Gen 7","Pokémon Ultra Moon"],["Gen 7","Pokémon Let's Go, Pikachu!"],["Gen 7","Pokémon Let's Go, Eevee!"]];
const bossTypes = ["Élite Four / Campeón","Líder de gimnasio","Rival","Equipo enemigo"];
const statLabels = ["hp","atk","def","spa","spd","spe"];
const typeClass = s => "type-" + String(s||"normal").toLowerCase().replace(/[^a-z]/g,"");
const typeEnglish = s => ({Normal:"normal",Fuego:"fire",Agua:"water",Eléctrico:"electric",Planta:"grass",Hielo:"ice",Lucha:"fighting",Veneno:"poison",Tierra:"ground",Volador:"flying",Psíquico:"psychic",Bicho:"bug",Roca:"rock",Fantasma:"ghost",Dragón:"dragon",Siniestro:"dark",Acero:"steel",Hada:"fairy"}[s] || String(s||"normal").toLowerCase());
let pokemonData = [];
let moves = [];
let state = loadState();
let currentView = {screen:"home",gameId:null,bossId:null,editing:false};
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{games:[]}}catch{return{games:[]}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(prefix){return prefix+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pokemonSprite(p){return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.dex}.png`}
function getGame(){return state.games.find(g=>g.id===currentView.gameId)}
function getBoss(){return getGame()?.bosses.find(b=>b.id===currentView.bossId)}
function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2200)}
async function loadData(){
  try{const res=await fetch("data/pokemon.json");pokemonData=await res.json()}catch(e){toast("No se pudo cargar la base de Pokémon.")}
  try{
    const cached=localStorage.getItem("boss-creator-moves");if(cached)moves=JSON.parse(cached);
    const res=await fetch(MOVE_URL);const all=await res.json();
    moves=all.filter(m=>Number(m.id)<=735);localStorage.setItem("boss-creator-moves",JSON.stringify(moves));
  }catch(e){if(!moves.length)toast("No se pudo cargar la base de movimientos. Revisa la conexión.")}
  render();
}
function render(){document.querySelector("#app").innerHTML=currentView.screen==="home"?renderHome():renderWorkspace();bindEvents()}
function renderHome(){return `<div class="app-shell">${renderSidebar()}<main class="main"><header class="topbar"><button class="mobile-menu" data-action="toggle-menu">☰</button><div class="topbar-title">Boss Creator</div><div></div></header><div class="content"><section class="hero"><div class="hero-card"><h1 class="pixel-title">BOSS CREATOR</h1><p>Crea tus propios jefes de Nuzlocke, añade sus Pokémon, movimientos, habilidad y objeto, y genera una guía visual lista para consultar durante la partida.</p><button class="btn btn-primary" data-action="new-game">＋ New Game</button></div></section></div></main></div>`}
function renderSidebar(){const activeGame=getGame();return `<aside class="sidebar" id="sidebar"><div class="brand"><h1>Boss Creator</h1><small>Nuzlocke Tracker</small></div><div class="side-section"><div class="side-title"><span>Mis juegos</span><button class="btn btn-primary" style="padding:6px 8px;font-size:11px" data-action="new-game">＋</button></div><div class="game-nav">${state.games.length?state.games.map(g=>`<button class="game-item ${g.id===currentView.gameId?"active":""}" data-game="${g.id}"><strong>${esc(g.name)}</strong><span>${esc(g.gen)} · ${g.bosses.length} boss${g.bosses.length===1?"":"es"}</span></button>`).join(""):``<div class="empty-side">Todavía no hay partidas guardadas.</div>``}</div>${activeGame?`<div class="side-title" style="margin-top:20px"><span>Bosses</span></div><div class="boss-list">${activeGame.bosses.length?activeGame.bosses.map(b=>`<button class="boss-nav ${b.id===currentView.bossId?"active":""}" data-boss="${b.id}">${esc(b.name)}</button>`).join(""):`<div class="empty-side">Crea el primer boss de esta partida.</div>`}</div><button class="btn btn-secondary" style="width:100%;margin-top:10px;justify-content:center" data-action="new-boss">＋ Crear boss</button>`:""}</div></aside>`}
function renderWorkspace(){const game=getGame();if(!game)return renderHome();const boss=getBoss();return `<div class="app-shell">${renderSidebar()}<main class="main"><header class="topbar"><button class="mobile-menu" data-action="toggle-menu">☰</button><div class="topbar-title">${esc(game.name)}</div><button class="btn btn-secondary" data-action="new-boss">＋ Crear boss</button></header><div class="content">${!boss?renderGameDashboard(game):renderBossPage(game,boss)}</div></main></div>`}
function renderGameDashboard(game){return `<div class="page-head"><div><h2>${esc(game.name)}</h2><p>${esc(game.gen)} · ${game.bosses.length} bosses guardados</p></div><button class="btn btn-primary" data-action="new-boss">＋ Crear boss</button></div><div class="grid-games">${game.bosses.map(b=>`<article class="game-card"><div class="gen">${esc(b.type)}</div><h3>${esc(b.name)}</h3><div class="count">${b.pokemon.length} Pokémon · ${b.finished?"Guía terminada":"En edición"}</div><button class="btn btn-secondary" data-boss="${b.id}">Abrir</button></article>`).join("")||`<div class="panel panel-pad"><p class="help">Aún no tienes bosses. Pulsa “Crear boss” para empezar.</p></div>`}</div>`}
function renderBossPage(game,boss){const editing=currentView.editing||!boss.finished;return `<div class="page-head"><div><h2>${esc(boss.name)}</h2><p>${esc(boss.type)} · ${game.name}</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-secondary" data-action="back-game">← Volver</button>${boss.finished&&!currentView.editing?`<button class="btn btn-primary" data-action="edit-boss">Editar</button>`:""}</div></div>${editing?renderBossEditor(boss):renderGuide(boss)}`}
function renderBossEditor(boss){return `<div class="workspace"><section class="panel"><div class="boss-hero">${boss.photo?`<img class="boss-photo" src="${boss.photo}" alt="">`:`<div class="boss-photo placeholder">👤</div>`}<div class="boss-meta"><span class="tag">${esc(boss.type)}</span><h2>${esc(boss.name)}</h2><p>${boss.pokemon.length} Pokémon configurados</p></div></div><div class="panel-pad"><div class="section-head"><h3>Equipo del boss</h3><button class="btn btn-primary" data-action="add-pokemon">＋ Agregar Pokémon</button></div>${boss.pokemon.length?`<div class="pokemon-list">${boss.pokemon.map((p,i)=>renderPokemonEditor(p,i)).join("")}</div>`:`<div class="notice">Añade Pokémon para construir el equipo. Cada uno tiene cuatro huecos de movimientos, habilidad, objeto y nivel.</div>`}<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:18px"><button class="btn btn-secondary" data-action="save-boss">Guardar cambios</button><button class="btn btn-primary" data-action="finish">Finish ✓</button></div></div></section><aside class="panel side-card"><div class="panel-pad"><div class="section-head"><h3>Datos del boss</h3></div><div class="form-grid"><div class="field full"><label>Nombre</label><input data-boss-field="name" value="${esc(boss.name)}"></div><div class="field full"><label>Tipo</label><select data-boss-field="type">${bossTypes.map(t=>`<option ${t===boss.type?"selected":""}>${esc(t)}</option>`).join("")}</select></div><div class="field full"><label>Foto del boss</label><input class="photo-input" type="file" accept="image/*" data-boss-photo><span class="help">Se guarda en este navegador. La imagen se reduce automáticamente.</span></div></div><div style="margin-top:16px"><button class="btn btn-danger" style="width:100%;justify-content:center" data-action="delete-boss">Eliminar boss</button></div></div></aside></div>`}
function renderPokemonEditor(entry){const p=pokemonData.find(x=>x[0]===entry.pokemonId)||pokemonData[0];const abilities=p?p[6]:[];const moveOptions=`<option value="">— Elegir movimiento —</option>`+moves.map(m=>`<option value="${m.id}">${esc(m.name.english)}</option>`).join("");return `<article class="poke-editor"><div class="poke-editor-head"><img class="poke-mini" src="${pokemonSprite({dex:p?.[2]||1})}" alt=""><div><strong>${esc(p?.[1]||"Pokémon")}</strong><span>#${String(p?.[2]||"").padStart(3,"0")} · ${esc(p?.[7]||"")}</span></div><button class="btn btn-danger remove" data-action="remove-pokemon" data-pokemon-id="${entry.id}">Eliminar</button></div><div class="poke-body"><div class="form-grid"><div class="field full"><label>Pokémon</label><select data-poke-field="pokemonId" data-pokemon-entry="${entry.id}">${pokemonData.map(x=>`<option value="${x[0]}" ${x[0]===entry.pokemonId?"selected":""}>#${String(x[2]).padStart(3,"0")} · ${esc(x[1])}</option>`).join("")}</select></div><div class="field"><label>Nivel</label><input type="number" min="1" max="100" data-poke-field="level" data-pokemon-entry="${entry.id}" value="${entry.level||50}"></div><div class="field"><label>Habilidad</label><select data-poke-field="ability" data-pokemon-entry="${entry.id}">${abilities.map(a=>`<option ${a===entry.ability?"selected":""}>${esc(a)}</option>`).join("")}</select></div><div class="field full"><label>Objeto</label><input data-poke-field="item" data-pokemon-entry="${entry.id}" value="${esc(entry.item||"")}" placeholder="Ej. Restos"></div></div><div style="margin-top:14px"><div class="section-head"><h3>Moveset</h3><small>4 movimientos</small></div><div class="moves-grid">${[0,1,2,3].map(i=>`<div class="field"><label>Movimiento ${i+1}</label><select data-move-slot="${i}" data-pokemon-entry="${entry.id}">${moveOptions.replace(`value="${entry.moves?.[i]||""}"`,`value="${entry.moves?.[i]||""}" selected`)}</select></div>`).join("")}</div></div></div></article>`}
function renderGuide(boss){return `<div class="panel"><div class="boss-hero">${boss.photo?`<img class="boss-photo" src="${boss.photo}" alt="">`:`<div class="boss-photo placeholder">👤</div>`}<div class="boss-meta"><span class="tag">${esc(boss.type)}</span><h2>${esc(boss.name)}</h2><p>Guía final · ${boss.pokemon.length} Pokémon</p></div><div class="boss-actions"><button class="btn btn-secondary" data-action="edit-boss">Editar</button></div></div><div class="guide-wrap"><div class="guide-card">${boss.pokemon.map(renderGuidePokemon).join("")}</div></div><div class="panel-pad" style="display:flex;justify-content:flex-end"><button class="btn btn-primary" data-action="edit-boss">Editar boss</button></div></div>`}
function renderGuidePokemon(entry){const p=pokemonData.find(x=>x[0]===entry.pokemonId)||pokemonData[0];const types=(p?.[7]||"Normal").split("/").map(s=>s.trim());const stats=p?.[4]||[0,0,0,0,0,0];const selected=(entry.moves||[]).map(id=>moves.find(m=>String(m.id)===String(id))).filter(Boolean);return `<section class="guide-poke"><div class="guide-top"><div class="guide-type">${esc(types[0])}</div><div class="guide-info"><div class="level">Level<b>${esc(entry.level||50)}</b></div><div class="name">${esc(p?.[1]||"Pokémon")}</div></div><img class="guide-sprite" src="${pokemonSprite({dex:p?.[2]||1})}" alt="${esc(p?.[1]||"")}"></div><div class="guide-body"><div class="guide-moves">${[0,1,2,3].map(i=>{const m=selected[i];if(!m)return `<div class="guide-move"><div class="move-name">—</div><div class="sub"><span class="move-chip type-normal">SIN MOVIMIENTO</span></div></div>`;const power=(m.power==="—"||m.power==="")?"—":String(m.power).replace("*","");return `<div class="guide-move"><div class="move-name">${esc(m.name.english)} <span class="move-power">✕${esc(power)}</span></div><div class="sub"><span class="move-chip ${typeClass(typeEnglish(m.type))}">${esc(m.type)}</span><span class="move-chip type-normal">${esc(m.category)}</span></div></div>`}).join("")}</div><div class="guide-stats">${stats.map((v,i)=>`<div class="stat-row"><span class="label">${statLabels[i]}</span><div class="bar"><i style="width:${Math.min(100,(v/180)*100)}%"></i></div><span class="value">${v}</span></div>`).join("")}</div></div><div class="guide-footer">Habilidad: <b>${esc(entry.ability||"—")}</b> · Objeto: <b>${esc(entry.item||"—")}</b> · BST ${esc(p?.[5]||"—")}</div></section>`}
function bindEvents(){
  document.querySelectorAll("[data-action]").forEach(el=>el.addEventListener("click",()=>handleAction(el.dataset.action,el)));
  document.querySelectorAll("[data-game]").forEach(el=>el.addEventListener("click",()=>{currentView={screen:"workspace",gameId:el.dataset.game,bossId:null,editing:false};render()}));
  document.querySelectorAll("[data-boss]").forEach(el=>el.addEventListener("click",()=>{currentView={screen:"workspace",gameId:currentView.gameId,bossId:el.dataset.boss,editing:false};render()}));
  document.querySelectorAll("[data-boss-field]").forEach(el=>el.addEventListener("input",()=>{const b=getBoss();if(!b)return;b[el.dataset.bossField]=el.value;saveState()}));
  document.querySelectorAll("[data-poke-field]").forEach(el=>el.addEventListener("change",()=>updatePokemonField(el)));
  document.querySelectorAll("[data-move-slot]").forEach(el=>el.addEventListener("change",()=>updateMove(el)));
  const photo=document.querySelector("[data-boss-photo]");if(photo)photo.addEventListener("change",handlePhoto);
}
function handleAction(action,el){if(action==="toggle-menu")document.querySelector("#sidebar")?.classList.toggle("open");if(action==="new-game")openGameModal();if(action==="new-boss")openBossModal();if(action==="add-pokemon")addPokemon();if(action==="remove-pokemon")removePokemon(el.dataset.pokemonId);if(action==="save-boss"){saveState();toast("Cambios guardados.");render()}if(action==="finish")finishBoss();if(action==="edit-boss"){currentView.editing=true;render()}if(action==="back-game"){currentView.bossId=null;currentView.editing=false;render()}if(action==="delete-boss")deleteBoss()}
function openGameModal(){document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="modal"><div class="modal"><div class="modal-head"><h3>New Game</h3><button class="btn btn-ghost" data-close-modal>✕</button></div><div class="modal-body"><p class="help" style="margin-top:0">Elige cualquier juego de las generaciones 1–7.</p><div class="game-select-grid">${games.map((g,i)=>`<button class="game-option" data-create-game="${i}"><strong>${esc(g[1])}</strong><span>${esc(g[0])}</span></button>`).join("")}</div></div></div></div>`);document.querySelectorAll("[data-create-game]").forEach(b=>b.onclick=()=>{const [gen,name]=games[Number(b.dataset.createGame)];const game={id:uid("game"),gen,name,bosses:[]};state.games.push(game);saveState();currentView={screen:"workspace",gameId:game.id,bossId:null,editing:false};closeModal();render();toast("Juego creado.")});document.querySelector("[data-close-modal]").onclick=closeModal}
function openBossModal(){if(!getGame())return;document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="modal"><div class="modal"><div class="modal-head"><h3>Crear boss</h3><button class="btn btn-ghost" data-close-modal>✕</button></div><div class="modal-body"><div class="form-grid"><div class="field full"><label>Tipo de boss</label><select id="newBossType">${bossTypes.map(x=>`<option>${esc(x)}</option>`).join("")}</select></div><div class="field full"><label>Nombre</label><input id="newBossName" placeholder="Ej. Líder Erika"></div><div class="field full"><label>Foto</label><input id="newBossPhoto" class="photo-input" type="file" accept="image/*"><span class="help">Opcional.</span></div></div></div><div class="modal-foot"><button class="btn btn-secondary" data-close-modal>Cancelar</button><button class="btn btn-primary" id="createBoss">Crear boss</button></div></div></div>`);document.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=closeModal);document.querySelector("#createBoss").onclick=async()=>{const name=document.querySelector("#newBossName").value.trim();if(!name){toast("Ponle un nombre al boss.");return}const file=document.querySelector("#newBossPhoto").files[0];const photo=file?await resizeImage(file):"";const b={id:uid("boss"),name,type:document.querySelector("#newBossType").value,photo,pokemon:[],finished:false};getGame().bosses.push(b);saveState();currentView.bossId=b.id;currentView.editing=true;closeModal();render()}}
function closeModal(){document.querySelector("#modal")?.remove()}
function addPokemon(){const b=getBoss();if(!b)return;const p=pokemonData[0];b.pokemon.push({id:uid("poke"),pokemonId:p[0],level:50,ability:p[6][0]||"",item:"",moves:["","",""]});b.pokemon.at(-1).moves=["","","",""];saveState();currentView.editing=true;render()}
function updatePokemonField(el){const b=getBoss();const p=b?.pokemon.find(x=>x.id===el.dataset.pokemonEntry);if(!p)return;const key=el.dataset.pokeField;if(key==="pokemonId"){p.pokemonId=Number(el.value);const data=pokemonData.find(x=>x[0]===p.pokemonId);p.ability=data?.[6]?.[0]||""}else p[key]=el.value;saveState();render()}
function updateMove(el){const b=getBoss();const p=b?.pokemon.find(x=>x.id===el.dataset.pokemonEntry);if(!p)return;p.moves[Number(el.dataset.moveSlot)]=el.value;saveState()}
function removePokemon(id){const b=getBoss();if(!b)return;b.pokemon=b.pokemon.filter(p=>p.id!==id);saveState();render();toast("Pokémon eliminado.")}
function finishBoss(){const b=getBoss();if(!b)return;if(!b.pokemon.length){toast("Añade al menos un Pokémon antes de Finish.");return}b.finished=true;saveState();currentView.editing=false;render();toast("Guía generada.")}
function deleteBoss(){const b=getBoss(),g=getGame();if(!b||!g)return;if(!confirm(`¿Eliminar "${b.name}"?`))return;g.bosses=g.bosses.filter(x=>x.id!==b.id);saveState();currentView.bossId=null;currentView.editing=false;render()}
async function handlePhoto(e){const b=getBoss(),file=e.target.files[0];if(!b||!file)return;b.photo=await resizeImage(file);saveState();render();toast("Foto actualizada.")}
function resizeImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=500,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.82))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
document.addEventListener("click",e=>{if(e.target.classList.contains("modal-backdrop"))closeModal()});
loadData();
